=== oicana/oicana-example-templates/templates/invoice_zugferd/invoice.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nikl.me/invoice.schema.json",
    "title": "Invoice",
    "description": "Invoice data to compile the template",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "id",
        "biller",
        "recipient",
        "issuingDate",
        "dueDate",
        "deliveryDate",
        "items"
    ],
    "properties": {
        "id": {
            "description": "Id of the invoice",
            "type": "string"
        },
        "$schema": {
            "type": "string"
        },
        "issuingDate": {
            "description": "Date at which the invoice is issued",
            "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
            "type": "string"
        },
        "deliveryDate": {
            "description": "Date at which the invoice is delivered",
            "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
            "type": "string"
        },
        "dueDate": {
            "description": "Date at which the invoice is due",
            "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
            "type": "string"
        },
        "biller": {
            "type": "object",
            "required": [
                "iban"
            ],
            "$ref": "#/$defs/contact"
        },
        "recipient": {
            "type": "object",
            "$ref": "#/$defs/contact"
        },
        "items": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "date",
                    "description",
                    "price"
                ],
                "properties": {
                    "date": {
                        "description": "Date When this item was completed",
                        "type": "string"
                    },
                    "description": {
                        "description": "Date When this item was completed",
                        "type": "string"
                    },
                    "quantity": {
                        "description": "Date When this item was completed",
                        "type": "number"
                    },
                    "dur-min": {
                        "description": "Date When this item was completed",
                        "type": "number"
                    },
                    "price": {
                        "description": "Date When this item was completed",
                        "type": "number"
                    }
                }
            }
        }
    },
    "$defs": {
        "contact": {
            "description": "A contact used in invoice data",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "name",
                "title",
                "iban",
                "vat-id",
                "company",
                "address"
            ],
            "properties": {
                "name": {
                    "description": "Name of the contact",
                    "type": "string"
                },
                "title": {
                    "description": "Title of the contact",
                    "type": "string"
                },
                "company": {
                    "description": "Company of the contact",
                    "type": "string"
                },
                "vat-id": {
                    "description": "Vat id  of the contact",
                    "minLength": 9,
                    "type": "string"
                },
                "iban": {
                    "description": "Iban of the contact",
                    "type": "string"
                },
                "address": {
                    "type": "object",
                    "additionalProperties": false,
                    "description": "Address data of the contact",
                    "required": ["country", "city", "postal-code", "street"],
                    "properties": {
                        "country": {
                            "description": "Country",
                            "type": "string"
                        },
                        "city": {
                            "description": "City",
                            "type": "string"
                        },
                        "postal-code": {
                            "description": "Postal code",
                            "type": "string"
                        },
                        "street": {
                            "description": "Street",
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== oicana/oicana-example-templates/templates/invoice_zugferd/invoice.json
{
  "$schema": "invoice.schema.json",
  "id": "2024-03-10t172205",
  "issuingDate": "2024-04-27",
  "deliveryDate": "2024-04-19",
  "dueDate": "2024-05-06",
  "biller": {
    "name": "Gyro Gearloose",
    "title": "Inventor",
    "company": "dsadsa Inventions Ltd.",
    "vat-id": "DL1234567",
    "iban": "DE89370400440532013000",
    "address": {
      "country": "Disneyland",
      "city": "Duckburg",
      "postal-code": "123456",
      "street": "Inventor Drive 23"
    }
  },
  "recipient": {
    "name": "Scrooge McDuck",
    "title": "Treasure Hunter",
    "vat-id": "DL7654321",
    "company": "dsadsa Inventions Ltd.",
    "iban": "DE89370400440532013000",
    "address": {
      "country": "Disneyland",
      "city": "Duckburg",
      "postal-code": "123456",
      "street": "Killmotor Hill 1"
    }
  },
  "items": [
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-03",
      "description": "Arc reactor",
      "quantity": 1,
      "price": 130
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-07",
      "description": "Lightsaber",
      "quantity": 2,
      "price": 3600
    },
    {
      "date": "2016-04-08",
      "description": "Sonic screwdriver",
      "quantity": 10,
      "price": 800
    },
    {
      "date": "2016-04-12",
      "description": "Assembly",
      "dur-min": 160,
      "price": 53.33
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-07",
      "description": "Lightsaber fdsf",
      "quantity": 2,
      "price": 3600
    },
    {
      "date": "2016-04-08",
      "description": "Sonic screwdriver",
      "quantity": 10,
      "price": 800
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-07",
      "description": "Lightsaber fdsjifbdsjfb dsfil dgfaui dgfdg FDA fagdfk dhgsfg zdsfk s",
      "quantity": 2,
      "price": 3600
    },
    {
      "date": "2016-04-08",
      "description": "Sonic screwdriver",
      "quantity": 10,
      "price": 800
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-07",
      "description": "Lightsaber",
      "quantity": 2,
      "price": 3600
    },
    {
      "date": "2016-04-08",
      "description": "Sonic screwdriver",
      "quantity": 10,
      "price": 800
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-07",
      "description": "Lightsaber",
      "quantity": 2,
      "price": 3600
    },
    {
      "date": "2016-04-08",
      "description": "Sonic screwdriver",
      "quantity": 10,
      "price": 800
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    },
    {
      "date": "2016-04-07",
      "description": "Lightsaber",
      "quantity": 2,
      "price": 3600
    },
    {
      "date": "2016-04-08",
      "description": "Sonic screwdriver",
      "quantity": 10,
      "price": 800
    },
    {
      "date": "2016-04-05",
      "description": "Flux capacitor",
      "quantity": 1,
      "price": 2700
    }
  ]
}
